// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// themeConfig.js
export const SIDEBAR_COLLASPED = 'SIDEBAR_COLLASPED'
export const MOBILE_NAV_COLLASPED = 'MOBILE_NAV_COLLASPED'
export const DARK_MODE = 'DARK_MODE'

// breadcrumbs.js
export const BREADCRUMBS = 'BREADCRUMBS'

// rolePermission.js
export const FETCH_ROLES = 'FETCH_ROLES'
export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS'
export const DELETE_ROLE = 'DELETE_ROLE'

// team.js
export const FETCH_TEAMS = 'FETCH_TEAMS'
export const FETCH_ALL_TEAMS = 'FETCH_ALL_TEAMS'
export const DELETE_TEAM = 'DELETE_TEAM'
export const DELETE_SELECTED_TEAM = 'DELETE_SELECTED_TEAM'

// tag.js
export const FETCH_TAGS     = 'FETCH_TAGS'
export const FETCH_ALL_TAGS = 'FETCH_ALL_TAGS'
export const UPDATE_TAGS    = 'UPDATE_TAGS'
export const DELETE_TAG     = 'DELETE_TAG'
export const DELETE_TAGS    = 'DELETE_TAGS'


// service.js
export const FETCH_CURRENCY = 'FETCH_CURRENCY'


// service.js
export const FETCH_SERVICES = 'FETCH_SERVICES'
export const FETCH_ALL_SERVICES = 'FETCH_ALL_SERVICES'
export const SELECTED_CHECKBOX = 'SELECTED_CHECKBOX'
export const SELECTED_SERVICES = 'SELECTED_SERVICES'
export const FORM_ERRORS = 'FORM_ERRORS'
export const INPUT_SERVICE_NAME = 'INPUT_SERVICE_NAME'
export const INPUT_SERVICE_DESC = 'INPUT_SERVICE_DESC'
export const INPUT_SERVICE_TEAMS = 'INPUT_SERVICE_TEAMS'
export const INPUT_SERVICE_TAGS = 'INPUT_SERVICE_TAGS'
export const ADD_SERVICE_TAGS = 'ADD_SERVICE_TAGS'
export const INPUT_SERVICE_TYPE = 'INPUT_SERVICE_TYPE'
export const INPUT_ONE_TIME_SERVICE_PRICE = 'INPUT_ONE_TIME_SERVICE_PRICE'
export const INPUT_ONE_IS_MULTI_ORDER = 'INPUT_ONE_IS_MULTI_ORDER'
export const INPUT_ONE_TIME_SERVICE_QTY = 'INPUT_ONE_TIME_SERVICE_QTY'
export const INPUT_CURRENCY = 'INPUT_CURRENCY'
export const REQUIRING_SERVICE_PRICE = 'REQUIRING_SERVICE_PRICE'
export const REQUIRING_SERVICE_PERIOD = 'REQUIRING_SERVICE_PERIOD'
export const REQUIRING_SERVICE_PERIOD_FOR = 'REQUIRING_SERVICE_PERIOD_FOR'
export const REQUIRING_SERVICE_IS_TRAIL = 'REQUIRING_SERVICE_IS_TRAIL'
export const SERVICE_TRAIL_PRICE = 'SERVICE_TRAIL_PRICE'
export const SERVICE_TRAIL_PERIOD = 'SERVICE_TRAIL_PERIOD'
export const SERVICE_TRAIL_FOR = 'SERVICE_TRAIL_FOR'
export const REQUIRING_SERVICE_STATUS = 'REQUIRING_SERVICE_STATUS'
export const REQUIRING_REQUEST_QUANTITY = 'REQUIRING_REQUEST_QUANTITY'
export const DELETE_SERVICES = 'REQUIRING_REQUEST_QUANTITY'
export const SERVICE_IMAGES = 'SERVICE_IMAGES'
export const SERVICE_REVIEW = 'SERVICE_REVIEW'
export const SERVICE_GROUP_QUANTITY = 'SERVICE_GROUP_QUANTITY'
export const SERVICE_HAS_DEADLINE = 'SERVICE_HAS_DEADLINE'
export const SERVICE_DEADLINE = 'SERVICE_DEADLINE'
export const SERVICE_DEADLINE_FOR = 'SERVICE_DEADLINE_FOR'
export const SERVICE_STATUS = 'SERVICE_STATUS'
export const DELETE_SERVICE = 'DELETE_SERVICE'
export const DELETE_SELECTED_SERVICE = 'DELETE_SELECTED_SERVICE'
export const DELETE_SERVICE_IMG = 'DELETE_SERVICE_IMG'



// orderForm.js
export const FETCH_ALL_ORDER_FORMS                   = 'FETCH_ALL_ORDER_FORMS'
export const INPUT_ORDER_FORM_NAME                   = 'INPUT_ORDER_FORM_NAME'
export const INPUT_ORDER_FORM_DESCRIPTION            = 'INPUT_ORDER_FORM_DESCRIPTION'
export const INPUT_ORDER_FORM_CUPON                  = 'INPUT_ORDER_FORM_CUPON'
export const INPUT_ORDER_FORM_FIELDS                 = 'INPUT_ORDER_FORM_FIELDS'
export const INPUT_ACTIVE_FORM                       = 'INPUT_ACTIVE_FORM'
export const INPUT_ELEMENT_INPUT                     = 'INPUT_ELEMENT_INPUT'
export const INPUT_INFO_FIELDS                       = 'INPUT_INFO_FIELDS'
export const INPUT_PAYMENT_FIELD                     = 'INPUT_PAYMENT_FIELD'
export const CLEAR_INPUT_AND_RESTORE_NAME            = 'CLEAR_INPUT_AND_RESTORE_NAME'
export const CLEAR_INPUT_AND_RESTORE_EMAIL           = 'CLEAR_INPUT_AND_RESTORE_EMAIL'
export const CLEAR_INPUT_AND_RESTORE_PASSWORD        = 'CLEAR_INPUT_AND_RESTORE_PASSWORD'
export const CLEAR_INPUT_AND_RESTORE_BILLING_ADDRESS = 'CLEAR_INPUT_AND_RESTORE_BILLING_ADDRESS'
export const CLEAR_INPUT_AND_RESTORE_PHONE           = 'CLEAR_INPUT_AND_RESTORE_PHONE'
export const CLEAR_INPUT_AND_RESTORE_PAYMENT         = 'CLEAR_INPUT_AND_RESTORE_PAYMENT'
export const DELETE_SELECTED_ORDER_FORM              = 'DELETE_SELECTED_ORDER_FORM'
export const DELETE_ORDER_FORM                       = 'DELETE_ORDER_FORM'